http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

pipeline.ordered: auto
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

queue.type: memory
queue.max_bytes: 1gb

log.level: info 